# Generated by Django 5.2.1 on 2025-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_evaluation_lesson_enrollment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
